export default {
  data: [
    {
      id: 1,
      month: "January",
      date: "Jan 3-7",
      ref: "Matthew 4:4",
      vers: "But he answered, “It is written, ‘Man shall not live by bread alone, but by every word that comes from the mouth of God.’”",
    },
    {
      id: 2,
      month: "January",
      date: "Jan 10-14",
      ref: "Matthew 6:33",
      vers: "But seek first the kingdom of God and his righteousness, and all these things will be added to you",
    },
    {
      id: 3,
      month: "January",
      date: "Jan 17-21",
      ref: "Matthew 11:28",
      vers: "Come to me, all who labor and are heavy laden, and I will give you rest.",
    },
    {
      id: 4,
      month: "January",
      date: "Jan 24-28",
      ref: "Matthew 19:14",
      vers: "But Jesus said, “Let the little children come to me and do not hinder them, for to such belongs the kingdom of heaven.”",
    },
    {
      id: 5,
      month: "January",
      date: "Jan 31 - Feb 4",
      ref: "Matthew 24:14",
      vers: "And this gospel of the kingdom will be proclaimed throughout the whole world as a testimony to all nations, and then the end will come.",
    },
    {
      id: 6,
      month: "February",
      date: "Feb 7-11",
      ref: "Matthew 28:18-20",
      vers: "And Jesus came and said to them, “All authority in heaven and on earth has been given to me. Go therefore and make disciples of all nations, baptizing them in the name of the Father and of the Son and of the Holy Spirit, teaching them to observe all that I have commanded you. And behold, I am with you always, to the end of the age.”",
    },
    {
      id: 7,
      month: "February",
      date: "Feb 14-18",
      ref: "Mark 1:17",
      vers: "And Jesus said to them, “Follow me, and I will make you become fishers of men.”",
    },
    {
      id: 8,
      month: "February",
      date: "Feb 21-25",
      ref: "Mark 8:31",
      vers: "And he began to teach them that the Son of Man must suffer many things and be rejected by the elders and the chief priests and the scribes and be killed, and after three days rise again.",
    },
    {
      id: 9,
      month: "February",
      date: "Feb 28 - Mar 4",
      ref: "Mark 14:38",
      vers: "Watch and pray that you may not enter into temptation. The spirit indeed is willing, but the flesh is weak.",
    },
    {
      id: 10,
      month: "March",
      date: "Mar 7-11",
      ref: "Luke 4:8",
      vers: "And Jesus answered him, “It is written, ‘You shall worship the Lord your God, and him only shall you serve.’”",
    },
    {
      id: 11,
      month: "March",
      date: "Mar 14-18",
      ref: "Luke 6:28",
      vers: "Bless those who curse you, pray for those who abuse you.",
    },
    {
      id: 12,
      month: "March",
      date: "Mar 21-25",
      ref: "Luke 11:28",
      vers: "But he said, “Blessed rather are those who hear the word of God and keep it!”",
    },
    {
      id: 13,
      month: "March",
      date: "Mar 28 - Apr 1",
      ref: "Luke 19:10",
      vers: "For the Son of Man came to seek and to save the lost.",
    },
    {
      id: 14,
      month: "April",
      date: "Apr 4-8",
      ref: "Luke 24:44",
      vers: "Then he said to them, “These are my words that I spoke to you while I was still with you, that everything written about me in the Law of Moses and the Prophets and the Psalms must be fulfilled.”",
    },
    {
      id: 15,
      month: "April",
      date: "Apr 11-15",
      ref: "John 5:18",
      vers: "This was why the Jews were seeking all the more to kill him, because not only was he breaking the Sabbath, but he was even calling God his own Father, making himself equal with God.",
    },
    {
      id: 16,
      month: "April",
      date: "Apr 18-22",
      ref: "John 8:12",
      vers: "Again Jesus spoke to them, saying, “I am the light of the world. Whoever follows me will not walk in darkness, but will have the light of life.”",
    },
    {
      id: 17,
      month: "April",
      date: "Apr 25-29",
      ref: "John 11:25",
      vers: "Jesus said to her, “I am the resurrection and the life.[a] Whoever believes in me, though he die, yet shall he live,",
    },
    {
      id: 18,
      month: "May",
      date: "May 2-6",
      ref: "John 16:33",
      vers: "I have said these things to you, that in me you may have peace. In the world you will have tribulation. But take heart; I have overcome the world.",
    },
    {
      id: 19,
      month: "May",
      date: "May 9-13",
      ref: "Acts 1:8",
      vers: "But you will receive power when the Holy Spirit has come upon you, and you will be my witnesses in Jerusalem and in all Judea and Samaria, and to the end of the earth.",
    },
    {
      id: 20,
      month: "May",
      date: "May 16-20",
      ref: "Acts 10:43",
      vers: "To him all the prophets bear witness that everyone who believes in him receives forgiveness of sins through his name.",
    },
    {
      id: 21,
      month: "May",
      date: "May 23-27",
      ref: "Acts 14:15",
      vers: "Men, why are you doing these things? We also are men, of like nature with you, and we bring you good news, that you should turn from these vain things to a living God, who made the heaven and the earth and the sea and all that is in them.",
    },
    {
      id: 22,
      month: "May",
      date: "May 30 - Jun 3",
      ref: "Acts 16:31",
      vers: "And they said, “Believe in the Lord Jesus, and you will be saved, you and your household.”",
    },
    {
      id: 23,
      month: "June",
      date: "Jun 6-10",
      ref: "Acts 24:16",
      vers: "So I always take pains to have a clear conscience toward both God and man.",
    },
    {
      id: 24,
      month: "June",
      date: "Jun 13-17",
      ref: "Acts 28:23",
      vers: "When they had appointed a day for him, they came to him at his lodging in greater numbers. From morning till evening he expounded to them, testifying to the kingdom of God and trying to convince them about Jesus both from the Law of Moses and from the Prophets.",
    },
    {
      id: 25,
      month: "June",
      date: "Jun 20-24",
      ref: "Romans 3:23",
      vers: "For all have sinned and fall short of the glory of God",
    },
    {
      id: 26,
      month: "June",
      date: "Jun 27 - July 1",
      ref: "Romans 10:9",
      vers: "Because, if you confess with your mouth that Jesus is Lord and believe in your heart that God raised him from the dead, you will be saved.",
    },
    {
      id: 27,
      month: "July",
      date: "July 4-8",
      ref: "Romans 12:1",
      vers: "I appeal to you therefore, brothers, by the mercies of God, to present your bodies as a living sacrifice, holy and acceptable to God, which is your spiritual worship.",
    },
    {
      id: 28,
      month: "July",
      date: "July 11-15",
      ref: "1 Corinthians 1:18",
      vers: "For the word of the cross is folly to those who are perishing, but to us who are being saved it is the power of God.",
    },
    {
      id: 29,
      month: "July",
      date: "July 18-22",
      ref: "1 Corinthians 10:13",
      vers: "No temptation has overtaken you that is not common to man. God is faithful, and he will not let you be tempted beyond your ability, but with the temptation he will also provide the way of escape, that you may be able to endure it.",
    },
    {
      id: 30,
      month: "July",
      date: "July 25-29",
      ref: "1 Corinthians 15:3-4",
      vers: "For I delivered to you as of first importance what I also received: that Christ died for our sins in accordance with the Scriptures, that he was buried, that he was raised on the third day in accordance with the Scriptures",
    },
    {
      id: 31,
      month: "August",
      date: "Aug 1-5",
      ref: "2 Corinthians 5:17 ",
      vers: "Therefore, if anyone is in Christ, he is a new creation. The old has passed away; behold, the new has come.",
    },
    {
      id: 32,
      month: "August",
      date: "Aug 8-12",
      ref: "2 Corinthians 6:14",
      vers: "Do not be unequally yoked with unbelievers. For what partnership has righteousness with lawlessness? Or what fellowship has light with darkness?",
    },
    {
      id: 33,
      month: "August",
      date: "Aug 15-19",
      ref: "2 Corinthians 12:9",
      vers: "But he said to me, “My grace is sufficient for you, for my power is made perfect in weakness.” Therefore I will boast all the more gladly of my weaknesses, so that the power of Christ may rest upon me.",
    },
    {
      id: 34,
      month: "August",
      date: "Aug 22-26",
      ref: "Galatians 2:20",
      vers: "I have been crucified with Christ. It is no longer I who live, but Christ who lives in me. And the life I now live in the flesh I live by faith in the Son of God, who loved me and gave himself for me.",
    },
    {
      id: 35,
      month: "August",
      date: "Aug 29 - Sept 2",
      ref: "Ephesians 2:8",
      vers: "For by grace you have been saved through faith. And this is not your own doing; it is the gift of God",
    },
    {
      id: 36,
      month: "September",
      date: "Sept 5-9",
      ref: "Philippians 4:6",
      vers: "Do not be anxious about anything, but in everything by prayer and supplication with thanksgiving let your requests be made known to God.",
    },
    {
      id: 37,
      month: "September",
      date: "Sept 12-16",
      ref: "Colossians 3:16",
      vers: "Let the word of Christ dwell in you richly, teaching and admonishing one another in all wisdom, singing psalms and hymns and spiritual songs, with thankfulness in your hearts to God.",
    },
    {
      id: 38,
      month: "September",
      date: "Sept 19-23",
      ref: "1 Thessalonians 5:17",
      vers: "Pray without ceasing",
    },
    {
      id: 39,
      month: "September",
      date: "Sept 26-30",
      ref: "2 Thessalonians 3:16",
      vers: "Now may the Lord of peace himself give you peace at all times in every way. The Lord be with you all.",
    },
    {
      id: 40,
      month: "October",
      date: "Oct 3-7",
      ref: "1 Timothy 3:16",
      vers: "Great indeed, we confess, is the mystery of godliness: He was manifested in the flesh, vindicated by the Spirit, seen by angels, proclaimed among the nations, believed on in the world, taken up in glory.",
    },
    {
      id: 41,
      month: "October",
      date: "Oct 10-14",
      ref: "2 Timothy 3:16-17",
      vers: "All Scripture is breathed out by God and profitable for teaching, for reproof, for correction, and for training in righteousness,  that the man of God may be complete, equipped for every good work.",
    },
    {
      id: 42,
      month: "October",
      date: "Oct 17-21",
      ref: "Titus 3:5",
      vers: "He saved us, not because of works done by us in righteousness, but according to his own mercy, by the washing of regeneration and renewal of the Holy Spirit,",
    },
    {
      id: 43,
      month: "October",
      date: "Oct 24-28",
      ref: "Hebrews 4:12",
      vers: "For the word of God is living and active, sharper than any two-edged sword, piercing to the division of soul and of spirit, of joints and of marrow, and discerning the thoughts and intentions of the heart.",
    },
    {
      id: 44,
      month: "October",
      date: "Oct 31 - Nov 4",
      ref: "Hebrews 9:27-28",
      vers: "And just as it is appointed for man to die once, and after that comes judgment, so Christ, having been offered once to bear the sins of many, will appear a second time, not to deal with sin but to save those who are eagerly waiting for him.",
    },
    {
      id: 45,
      month: "November",
      date: "Nov 7-11",
      ref: "James 5:16",
      vers: "Therefore, confess your sins to one another and pray for one another, that you may be healed. The prayer of a righteous person has great power as it is working.",
    },
    {
      id: 46,
      month: "November",
      date: "Nov 14-18",
      ref: "1 Peter 3:15",
      vers: "But in your hearts honor Christ the Lord as holy, always being prepared to make a defense to anyone who asks you for a reason for the hope that is in you; yet do it with gentleness and respect,",
    },
    {
      id: 47,
      month: "November",
      date: "Nov 21-25",
      ref: "2 Peter 3:9",
      vers: "The Lord is not slow to fulfill his promise as some count slowness, but is patient toward you, not wishing that any should perish, but that all should reach repentance.",
    },
    {
      id: 48,
      month: "November",
      date: "Nov 28 - Dec 2",
      ref: "1 John 1:9",
      vers: "If we confess our sins, he is faithful and just to forgive us our sins and to cleanse us from all unrighteousness.",
    },
    {
      id: 49,
      month: "December",
      date: "Dec 5-9",
      ref: "Revelation 3:20 ",
      vers: "Behold, I stand at the door and knock. If anyone hears my voice and opens the door, I will come in to him and eat with him, and he with me.",
    },
    {
      id: 50,
      month: "December",
      date: "Dec 12-16",
      ref: "Revelation 7:10",
      vers: "And crying out with a loud voice, “Salvation belongs to our God who sits on the throne, and to the Lamb!”",
    },
    {
      id: 51,
      month: "December",
      date: "Dec 19-23",
      ref: "Revelation 12:11",
      vers: "And they have conquered him by the blood of the Lamb and by the word of their testimony, for they loved not their lives even unto death.",
    },
    {
      id: 52,
      month: "December",
      date: "Dec 26-30",
      ref: "Revelation 22:17",
      vers: "The Spirit and the Bride say, “Come.” And let the one who hears say, “Come.” And let the one who is thirsty come; let the one who desires take the water of life without price.",
    },
  ],
};
